// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: order.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Order struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId            int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AssetId           int64                  `protobuf:"varint,3,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	OrderType         string                 `protobuf:"bytes,4,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"` // MARKET, LIMIT, STOP, STOP_LIMIT
	Quantity          int32                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ContractSize      int32                  `protobuf:"varint,6,opt,name=contract_size,json=contractSize,proto3" json:"contract_size,omitempty"`
	PricePerUnit      float64                `protobuf:"fixed64,7,opt,name=price_per_unit,json=pricePerUnit,proto3" json:"price_per_unit,omitempty"`
	LimitValue        float64                `protobuf:"fixed64,8,opt,name=limit_value,json=limitValue,proto3" json:"limit_value,omitempty"`
	StopValue         float64                `protobuf:"fixed64,9,opt,name=stop_value,json=stopValue,proto3" json:"stop_value,omitempty"`
	Direction         string                 `protobuf:"bytes,10,opt,name=direction,proto3" json:"direction,omitempty"` // BUY, SELL
	Status            string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`       // PENDING, APPROVED, DECLINED
	ApprovedBy        int64                  `protobuf:"varint,12,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	IsDone            bool                   `protobuf:"varint,13,opt,name=is_done,json=isDone,proto3" json:"is_done,omitempty"`
	LastModification  string                 `protobuf:"bytes,14,opt,name=last_modification,json=lastModification,proto3" json:"last_modification,omitempty"` // RFC3339
	RemainingPortions int32                  `protobuf:"varint,15,opt,name=remaining_portions,json=remainingPortions,proto3" json:"remaining_portions,omitempty"`
	AfterHours        bool                   `protobuf:"varint,16,opt,name=after_hours,json=afterHours,proto3" json:"after_hours,omitempty"`
	IsAon             bool                   `protobuf:"varint,17,opt,name=is_aon,json=isAon,proto3" json:"is_aon,omitempty"`
	IsMargin          bool                   `protobuf:"varint,18,opt,name=is_margin,json=isMargin,proto3" json:"is_margin,omitempty"`
	AccountId         int64                  `protobuf:"varint,19,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *Order) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Order) GetAssetId() int64 {
	if x != nil {
		return x.AssetId
	}
	return 0
}

func (x *Order) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

func (x *Order) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Order) GetContractSize() int32 {
	if x != nil {
		return x.ContractSize
	}
	return 0
}

func (x *Order) GetPricePerUnit() float64 {
	if x != nil {
		return x.PricePerUnit
	}
	return 0
}

func (x *Order) GetLimitValue() float64 {
	if x != nil {
		return x.LimitValue
	}
	return 0
}

func (x *Order) GetStopValue() float64 {
	if x != nil {
		return x.StopValue
	}
	return 0
}

func (x *Order) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetApprovedBy() int64 {
	if x != nil {
		return x.ApprovedBy
	}
	return 0
}

func (x *Order) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *Order) GetLastModification() string {
	if x != nil {
		return x.LastModification
	}
	return ""
}

func (x *Order) GetRemainingPortions() int32 {
	if x != nil {
		return x.RemainingPortions
	}
	return 0
}

func (x *Order) GetAfterHours() bool {
	if x != nil {
		return x.AfterHours
	}
	return false
}

func (x *Order) GetIsAon() bool {
	if x != nil {
		return x.IsAon
	}
	return false
}

func (x *Order) GetIsMargin() bool {
	if x != nil {
		return x.IsMargin
	}
	return false
}

func (x *Order) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\x05order\"\r\n" +
	"\vPingRequest\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xd1\x04\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x19\n" +
	"\basset_id\x18\x03 \x01(\x03R\aassetId\x12\x1d\n" +
	"\n" +
	"order_type\x18\x04 \x01(\tR\torderType\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x05R\bquantity\x12#\n" +
	"\rcontract_size\x18\x06 \x01(\x05R\fcontractSize\x12$\n" +
	"\x0eprice_per_unit\x18\a \x01(\x01R\fpricePerUnit\x12\x1f\n" +
	"\vlimit_value\x18\b \x01(\x01R\n" +
	"limitValue\x12\x1d\n" +
	"\n" +
	"stop_value\x18\t \x01(\x01R\tstopValue\x12\x1c\n" +
	"\tdirection\x18\n" +
	" \x01(\tR\tdirection\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12\x1f\n" +
	"\vapproved_by\x18\f \x01(\x03R\n" +
	"approvedBy\x12\x17\n" +
	"\ais_done\x18\r \x01(\bR\x06isDone\x12+\n" +
	"\x11last_modification\x18\x0e \x01(\tR\x10lastModification\x12-\n" +
	"\x12remaining_portions\x18\x0f \x01(\x05R\x11remainingPortions\x12\x1f\n" +
	"\vafter_hours\x18\x10 \x01(\bR\n" +
	"afterHours\x12\x15\n" +
	"\x06is_aon\x18\x11 \x01(\bR\x05isAon\x12\x1b\n" +
	"\tis_margin\x18\x12 \x01(\bR\bisMargin\x12\x1d\n" +
	"\n" +
	"account_id\x18\x13 \x01(\x03R\taccountId2?\n" +
	"\fOrderService\x12/\n" +
	"\x04Ping\x12\x12.order.PingRequest\x1a\x13.order.PingResponseB:Z8github.com/RAF-SI-2025/EXBanka-4-Backend/shared/pb/orderb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_order_proto_goTypes = []any{
	(*PingRequest)(nil),  // 0: order.PingRequest
	(*PingResponse)(nil), // 1: order.PingResponse
	(*Order)(nil),        // 2: order.Order
}
var file_order_proto_depIdxs = []int32{
	0, // 0: order.OrderService.Ping:input_type -> order.PingRequest
	1, // 1: order.OrderService.Ping:output_type -> order.PingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
