// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: fund.proto

package fund

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_fund_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fund_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_fund_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_fund_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fund_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_fund_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateFundRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description         string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	MinimumContribution float64                `protobuf:"fixed64,3,opt,name=minimum_contribution,json=minimumContribution,proto3" json:"minimum_contribution,omitempty"`
	ManagerId           int64                  `protobuf:"varint,4,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	CreatedById         int64                  `protobuf:"varint,5,opt,name=created_by_id,json=createdById,proto3" json:"created_by_id,omitempty"` // employee ID of creator
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateFundRequest) Reset() {
	*x = CreateFundRequest{}
	mi := &file_fund_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFundRequest) ProtoMessage() {}

func (x *CreateFundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fund_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFundRequest.ProtoReflect.Descriptor instead.
func (*CreateFundRequest) Descriptor() ([]byte, []int) {
	return file_fund_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFundRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateFundRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateFundRequest) GetMinimumContribution() float64 {
	if x != nil {
		return x.MinimumContribution
	}
	return 0
}

func (x *CreateFundRequest) GetManagerId() int64 {
	if x != nil {
		return x.ManagerId
	}
	return 0
}

func (x *CreateFundRequest) GetCreatedById() int64 {
	if x != nil {
		return x.CreatedById
	}
	return 0
}

type UpdateFundRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description         string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MinimumContribution float64                `protobuf:"fixed64,4,opt,name=minimum_contribution,json=minimumContribution,proto3" json:"minimum_contribution,omitempty"`
	ManagerId           int64                  `protobuf:"varint,5,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateFundRequest) Reset() {
	*x = UpdateFundRequest{}
	mi := &file_fund_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFundRequest) ProtoMessage() {}

func (x *UpdateFundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fund_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFundRequest.ProtoReflect.Descriptor instead.
func (*UpdateFundRequest) Descriptor() ([]byte, []int) {
	return file_fund_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateFundRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateFundRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateFundRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateFundRequest) GetMinimumContribution() float64 {
	if x != nil {
		return x.MinimumContribution
	}
	return 0
}

func (x *UpdateFundRequest) GetManagerId() int64 {
	if x != nil {
		return x.ManagerId
	}
	return 0
}

type DeleteFundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFundRequest) Reset() {
	*x = DeleteFundRequest{}
	mi := &file_fund_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFundRequest) ProtoMessage() {}

func (x *DeleteFundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fund_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFundRequest.ProtoReflect.Descriptor instead.
func (*DeleteFundRequest) Descriptor() ([]byte, []int) {
	return file_fund_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteFundRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteFundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFundResponse) Reset() {
	*x = DeleteFundResponse{}
	mi := &file_fund_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFundResponse) ProtoMessage() {}

func (x *DeleteFundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fund_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFundResponse.ProtoReflect.Descriptor instead.
func (*DeleteFundResponse) Descriptor() ([]byte, []int) {
	return file_fund_proto_rawDescGZIP(), []int{5}
}

type ListFundsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ManagerIdFilter int64                  `protobuf:"varint,1,opt,name=manager_id_filter,json=managerIdFilter,proto3" json:"manager_id_filter,omitempty"` // 0 = no filter
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListFundsRequest) Reset() {
	*x = ListFundsRequest{}
	mi := &file_fund_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFundsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFundsRequest) ProtoMessage() {}

func (x *ListFundsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fund_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFundsRequest.ProtoReflect.Descriptor instead.
func (*ListFundsRequest) Descriptor() ([]byte, []int) {
	return file_fund_proto_rawDescGZIP(), []int{6}
}

func (x *ListFundsRequest) GetManagerIdFilter() int64 {
	if x != nil {
		return x.ManagerIdFilter
	}
	return 0
}

type GetFundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFundRequest) Reset() {
	*x = GetFundRequest{}
	mi := &file_fund_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFundRequest) ProtoMessage() {}

func (x *GetFundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fund_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFundRequest.ProtoReflect.Descriptor instead.
func (*GetFundRequest) Descriptor() ([]byte, []int) {
	return file_fund_proto_rawDescGZIP(), []int{7}
}

func (x *GetFundRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FundResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description         string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MinimumContribution float64                `protobuf:"fixed64,4,opt,name=minimum_contribution,json=minimumContribution,proto3" json:"minimum_contribution,omitempty"`
	ManagerId           int64                  `protobuf:"varint,5,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	ManagerName         string                 `protobuf:"bytes,6,opt,name=manager_name,json=managerName,proto3" json:"manager_name,omitempty"`
	LiquidAssets        float64                `protobuf:"fixed64,7,opt,name=liquid_assets,json=liquidAssets,proto3" json:"liquid_assets,omitempty"`
	FundValue           float64                `protobuf:"fixed64,8,opt,name=fund_value,json=fundValue,proto3" json:"fund_value,omitempty"`
	Profit              float64                `protobuf:"fixed64,9,opt,name=profit,proto3" json:"profit,omitempty"`
	AccountNumber       string                 `protobuf:"bytes,10,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	CreatedAt           string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Active              bool                   `protobuf:"varint,12,opt,name=active,proto3" json:"active,omitempty"`
	AccountId           int64                  `protobuf:"varint,13,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FundResponse) Reset() {
	*x = FundResponse{}
	mi := &file_fund_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FundResponse) ProtoMessage() {}

func (x *FundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fund_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FundResponse.ProtoReflect.Descriptor instead.
func (*FundResponse) Descriptor() ([]byte, []int) {
	return file_fund_proto_rawDescGZIP(), []int{8}
}

func (x *FundResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FundResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FundResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FundResponse) GetMinimumContribution() float64 {
	if x != nil {
		return x.MinimumContribution
	}
	return 0
}

func (x *FundResponse) GetManagerId() int64 {
	if x != nil {
		return x.ManagerId
	}
	return 0
}

func (x *FundResponse) GetManagerName() string {
	if x != nil {
		return x.ManagerName
	}
	return ""
}

func (x *FundResponse) GetLiquidAssets() float64 {
	if x != nil {
		return x.LiquidAssets
	}
	return 0
}

func (x *FundResponse) GetFundValue() float64 {
	if x != nil {
		return x.FundValue
	}
	return 0
}

func (x *FundResponse) GetProfit() float64 {
	if x != nil {
		return x.Profit
	}
	return 0
}

func (x *FundResponse) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *FundResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *FundResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *FundResponse) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type ListFundsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Funds         []*FundResponse        `protobuf:"bytes,1,rep,name=funds,proto3" json:"funds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFundsResponse) Reset() {
	*x = ListFundsResponse{}
	mi := &file_fund_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFundsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFundsResponse) ProtoMessage() {}

func (x *ListFundsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fund_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFundsResponse.ProtoReflect.Descriptor instead.
func (*ListFundsResponse) Descriptor() ([]byte, []int) {
	return file_fund_proto_rawDescGZIP(), []int{9}
}

func (x *ListFundsResponse) GetFunds() []*FundResponse {
	if x != nil {
		return x.Funds
	}
	return nil
}

var File_fund_proto protoreflect.FileDescriptor

const file_fund_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"fund.proto\x12\x04fund\"\r\n" +
	"\vPingRequest\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xbf\x01\n" +
	"\x11CreateFundRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x121\n" +
	"\x14minimum_contribution\x18\x03 \x01(\x01R\x13minimumContribution\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x04 \x01(\x03R\tmanagerId\x12\"\n" +
	"\rcreated_by_id\x18\x05 \x01(\x03R\vcreatedById\"\xab\x01\n" +
	"\x11UpdateFundRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x121\n" +
	"\x14minimum_contribution\x18\x04 \x01(\x01R\x13minimumContribution\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x05 \x01(\x03R\tmanagerId\"#\n" +
	"\x11DeleteFundRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x14\n" +
	"\x12DeleteFundResponse\">\n" +
	"\x10ListFundsRequest\x12*\n" +
	"\x11manager_id_filter\x18\x01 \x01(\x03R\x0fmanagerIdFilter\" \n" +
	"\x0eGetFundRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xa2\x03\n" +
	"\fFundResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x121\n" +
	"\x14minimum_contribution\x18\x04 \x01(\x01R\x13minimumContribution\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x05 \x01(\x03R\tmanagerId\x12!\n" +
	"\fmanager_name\x18\x06 \x01(\tR\vmanagerName\x12#\n" +
	"\rliquid_assets\x18\a \x01(\x01R\fliquidAssets\x12\x1d\n" +
	"\n" +
	"fund_value\x18\b \x01(\x01R\tfundValue\x12\x16\n" +
	"\x06profit\x18\t \x01(\x01R\x06profit\x12%\n" +
	"\x0eaccount_number\x18\n" +
	" \x01(\tR\raccountNumber\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x16\n" +
	"\x06active\x18\f \x01(\bR\x06active\x12\x1d\n" +
	"\n" +
	"account_id\x18\r \x01(\x03R\taccountId\"=\n" +
	"\x11ListFundsResponse\x12(\n" +
	"\x05funds\x18\x01 \x03(\v2\x12.fund.FundResponseR\x05funds2\xe6\x02\n" +
	"\vFundService\x12-\n" +
	"\x04Ping\x12\x11.fund.PingRequest\x1a\x12.fund.PingResponse\x129\n" +
	"\n" +
	"CreateFund\x12\x17.fund.CreateFundRequest\x1a\x12.fund.FundResponse\x12<\n" +
	"\tListFunds\x12\x16.fund.ListFundsRequest\x1a\x17.fund.ListFundsResponse\x123\n" +
	"\aGetFund\x12\x14.fund.GetFundRequest\x1a\x12.fund.FundResponse\x129\n" +
	"\n" +
	"UpdateFund\x12\x17.fund.UpdateFundRequest\x1a\x12.fund.FundResponse\x12?\n" +
	"\n" +
	"DeleteFund\x12\x17.fund.DeleteFundRequest\x1a\x18.fund.DeleteFundResponseB9Z7github.com/RAF-SI-2025/EXBanka-4-Backend/shared/pb/fundb\x06proto3"

var (
	file_fund_proto_rawDescOnce sync.Once
	file_fund_proto_rawDescData []byte
)

func file_fund_proto_rawDescGZIP() []byte {
	file_fund_proto_rawDescOnce.Do(func() {
		file_fund_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fund_proto_rawDesc), len(file_fund_proto_rawDesc)))
	})
	return file_fund_proto_rawDescData
}

var file_fund_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_fund_proto_goTypes = []any{
	(*PingRequest)(nil),        // 0: fund.PingRequest
	(*PingResponse)(nil),       // 1: fund.PingResponse
	(*CreateFundRequest)(nil),  // 2: fund.CreateFundRequest
	(*UpdateFundRequest)(nil),  // 3: fund.UpdateFundRequest
	(*DeleteFundRequest)(nil),  // 4: fund.DeleteFundRequest
	(*DeleteFundResponse)(nil), // 5: fund.DeleteFundResponse
	(*ListFundsRequest)(nil),   // 6: fund.ListFundsRequest
	(*GetFundRequest)(nil),     // 7: fund.GetFundRequest
	(*FundResponse)(nil),       // 8: fund.FundResponse
	(*ListFundsResponse)(nil),  // 9: fund.ListFundsResponse
}
var file_fund_proto_depIdxs = []int32{
	8, // 0: fund.ListFundsResponse.funds:type_name -> fund.FundResponse
	0, // 1: fund.FundService.Ping:input_type -> fund.PingRequest
	2, // 2: fund.FundService.CreateFund:input_type -> fund.CreateFundRequest
	6, // 3: fund.FundService.ListFunds:input_type -> fund.ListFundsRequest
	7, // 4: fund.FundService.GetFund:input_type -> fund.GetFundRequest
	3, // 5: fund.FundService.UpdateFund:input_type -> fund.UpdateFundRequest
	4, // 6: fund.FundService.DeleteFund:input_type -> fund.DeleteFundRequest
	1, // 7: fund.FundService.Ping:output_type -> fund.PingResponse
	8, // 8: fund.FundService.CreateFund:output_type -> fund.FundResponse
	9, // 9: fund.FundService.ListFunds:output_type -> fund.ListFundsResponse
	8, // 10: fund.FundService.GetFund:output_type -> fund.FundResponse
	8, // 11: fund.FundService.UpdateFund:output_type -> fund.FundResponse
	5, // 12: fund.FundService.DeleteFund:output_type -> fund.DeleteFundResponse
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_fund_proto_init() }
func file_fund_proto_init() {
	if File_fund_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fund_proto_rawDesc), len(file_fund_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fund_proto_goTypes,
		DependencyIndexes: file_fund_proto_depIdxs,
		MessageInfos:      file_fund_proto_msgTypes,
	}.Build()
	File_fund_proto = out.File
	file_fund_proto_goTypes = nil
	file_fund_proto_depIdxs = nil
}
