// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: otc.proto

package otc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OtcService_Ping_FullMethodName              = "/otc.OtcService/Ping"
	OtcService_CreateNegotiation_FullMethodName = "/otc.OtcService/CreateNegotiation"
	OtcService_ListNegotiations_FullMethodName  = "/otc.OtcService/ListNegotiations"
	OtcService_GetNegotiation_FullMethodName    = "/otc.OtcService/GetNegotiation"
	OtcService_CounterOffer_FullMethodName      = "/otc.OtcService/CounterOffer"
	OtcService_AcceptNegotiation_FullMethodName = "/otc.OtcService/AcceptNegotiation"
	OtcService_RejectNegotiation_FullMethodName = "/otc.OtcService/RejectNegotiation"
)

// OtcServiceClient is the client API for OtcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OtcServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	CreateNegotiation(ctx context.Context, in *CreateNegotiationRequest, opts ...grpc.CallOption) (*NegotiationResponse, error)
	ListNegotiations(ctx context.Context, in *ListNegotiationsRequest, opts ...grpc.CallOption) (*ListNegotiationsResponse, error)
	GetNegotiation(ctx context.Context, in *GetNegotiationRequest, opts ...grpc.CallOption) (*NegotiationResponse, error)
	CounterOffer(ctx context.Context, in *CounterOfferRequest, opts ...grpc.CallOption) (*NegotiationResponse, error)
	AcceptNegotiation(ctx context.Context, in *AcceptNegotiationRequest, opts ...grpc.CallOption) (*NegotiationResponse, error)
	RejectNegotiation(ctx context.Context, in *RejectNegotiationRequest, opts ...grpc.CallOption) (*NegotiationResponse, error)
}

type otcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOtcServiceClient(cc grpc.ClientConnInterface) OtcServiceClient {
	return &otcServiceClient{cc}
}

func (c *otcServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, OtcService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *otcServiceClient) CreateNegotiation(ctx context.Context, in *CreateNegotiationRequest, opts ...grpc.CallOption) (*NegotiationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NegotiationResponse)
	err := c.cc.Invoke(ctx, OtcService_CreateNegotiation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *otcServiceClient) ListNegotiations(ctx context.Context, in *ListNegotiationsRequest, opts ...grpc.CallOption) (*ListNegotiationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNegotiationsResponse)
	err := c.cc.Invoke(ctx, OtcService_ListNegotiations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *otcServiceClient) GetNegotiation(ctx context.Context, in *GetNegotiationRequest, opts ...grpc.CallOption) (*NegotiationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NegotiationResponse)
	err := c.cc.Invoke(ctx, OtcService_GetNegotiation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *otcServiceClient) CounterOffer(ctx context.Context, in *CounterOfferRequest, opts ...grpc.CallOption) (*NegotiationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NegotiationResponse)
	err := c.cc.Invoke(ctx, OtcService_CounterOffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *otcServiceClient) AcceptNegotiation(ctx context.Context, in *AcceptNegotiationRequest, opts ...grpc.CallOption) (*NegotiationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NegotiationResponse)
	err := c.cc.Invoke(ctx, OtcService_AcceptNegotiation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *otcServiceClient) RejectNegotiation(ctx context.Context, in *RejectNegotiationRequest, opts ...grpc.CallOption) (*NegotiationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NegotiationResponse)
	err := c.cc.Invoke(ctx, OtcService_RejectNegotiation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OtcServiceServer is the server API for OtcService service.
// All implementations must embed UnimplementedOtcServiceServer
// for forward compatibility.
type OtcServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	CreateNegotiation(context.Context, *CreateNegotiationRequest) (*NegotiationResponse, error)
	ListNegotiations(context.Context, *ListNegotiationsRequest) (*ListNegotiationsResponse, error)
	GetNegotiation(context.Context, *GetNegotiationRequest) (*NegotiationResponse, error)
	CounterOffer(context.Context, *CounterOfferRequest) (*NegotiationResponse, error)
	AcceptNegotiation(context.Context, *AcceptNegotiationRequest) (*NegotiationResponse, error)
	RejectNegotiation(context.Context, *RejectNegotiationRequest) (*NegotiationResponse, error)
	mustEmbedUnimplementedOtcServiceServer()
}

// UnimplementedOtcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOtcServiceServer struct{}

func (UnimplementedOtcServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedOtcServiceServer) CreateNegotiation(context.Context, *CreateNegotiationRequest) (*NegotiationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNegotiation not implemented")
}
func (UnimplementedOtcServiceServer) ListNegotiations(context.Context, *ListNegotiationsRequest) (*ListNegotiationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNegotiations not implemented")
}
func (UnimplementedOtcServiceServer) GetNegotiation(context.Context, *GetNegotiationRequest) (*NegotiationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNegotiation not implemented")
}
func (UnimplementedOtcServiceServer) CounterOffer(context.Context, *CounterOfferRequest) (*NegotiationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CounterOffer not implemented")
}
func (UnimplementedOtcServiceServer) AcceptNegotiation(context.Context, *AcceptNegotiationRequest) (*NegotiationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptNegotiation not implemented")
}
func (UnimplementedOtcServiceServer) RejectNegotiation(context.Context, *RejectNegotiationRequest) (*NegotiationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectNegotiation not implemented")
}
func (UnimplementedOtcServiceServer) mustEmbedUnimplementedOtcServiceServer() {}
func (UnimplementedOtcServiceServer) testEmbeddedByValue()                    {}

// UnsafeOtcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OtcServiceServer will
// result in compilation errors.
type UnsafeOtcServiceServer interface {
	mustEmbedUnimplementedOtcServiceServer()
}

func RegisterOtcServiceServer(s grpc.ServiceRegistrar, srv OtcServiceServer) {
	// If the following call panics, it indicates UnimplementedOtcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OtcService_ServiceDesc, srv)
}

func _OtcService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OtcServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OtcService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OtcServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OtcService_CreateNegotiation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNegotiationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OtcServiceServer).CreateNegotiation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OtcService_CreateNegotiation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OtcServiceServer).CreateNegotiation(ctx, req.(*CreateNegotiationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OtcService_ListNegotiations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNegotiationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OtcServiceServer).ListNegotiations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OtcService_ListNegotiations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OtcServiceServer).ListNegotiations(ctx, req.(*ListNegotiationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OtcService_GetNegotiation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNegotiationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OtcServiceServer).GetNegotiation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OtcService_GetNegotiation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OtcServiceServer).GetNegotiation(ctx, req.(*GetNegotiationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OtcService_CounterOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CounterOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OtcServiceServer).CounterOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OtcService_CounterOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OtcServiceServer).CounterOffer(ctx, req.(*CounterOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OtcService_AcceptNegotiation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptNegotiationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OtcServiceServer).AcceptNegotiation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OtcService_AcceptNegotiation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OtcServiceServer).AcceptNegotiation(ctx, req.(*AcceptNegotiationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OtcService_RejectNegotiation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectNegotiationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OtcServiceServer).RejectNegotiation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OtcService_RejectNegotiation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OtcServiceServer).RejectNegotiation(ctx, req.(*RejectNegotiationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OtcService_ServiceDesc is the grpc.ServiceDesc for OtcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OtcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "otc.OtcService",
	HandlerType: (*OtcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _OtcService_Ping_Handler,
		},
		{
			MethodName: "CreateNegotiation",
			Handler:    _OtcService_CreateNegotiation_Handler,
		},
		{
			MethodName: "ListNegotiations",
			Handler:    _OtcService_ListNegotiations_Handler,
		},
		{
			MethodName: "GetNegotiation",
			Handler:    _OtcService_GetNegotiation_Handler,
		},
		{
			MethodName: "CounterOffer",
			Handler:    _OtcService_CounterOffer_Handler,
		},
		{
			MethodName: "AcceptNegotiation",
			Handler:    _OtcService_AcceptNegotiation_Handler,
		},
		{
			MethodName: "RejectNegotiation",
			Handler:    _OtcService_RejectNegotiation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "otc.proto",
}
